version: '3.7'
networks:
  backend:
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: production-stage
    container_name: api-gateway
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - auth
    volumes:
      - ./logs/api-gateway:/app/logs
    networks:
      - backend

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production-stage
    container_name: auth
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs/auth:/app/logs
    networks:
      - backend
    
  auth-db:
    image: mysql:5.7
    container_name: auth-db
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
    volumes:
      - ./mysql-data/auth:/var/lib/mysql
    networks:
    - backend
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend